version: 2
jobs:
  one:
    docker:
        - image: circleci/node
    steps:
        - checkout
        - run: yarn install
        - run: yarn test
workflows:
    version: 2
    run_test:
        jobs:
            - test_frontend
